# Example application deployment
# This is a simple nginx deployment to test Fleet

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
  namespace: default
  labels:
    app: nginx-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  namespace: default
spec:
  selector:
    app: nginx-example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
