apiVersion: v1
kind: ConfigMap
metadata:
  name: phpldapadmin-env
data:
  PHPLDAPADMIN_LDAP_HOSTS: "openldap.openldap.svc.cluster.local"
  PHPLDAPADMIN_HTTPS: "false"
  PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
